### ISSUE TITLE
Phishing domain

### ISSUE THREAD

**Issue by kuba256** [Andre601/anti-scam-database#17]
### Confirmation

- [X] I've read the [Contributing file](https://github.com/Andre601/anti-scam-database/blob/main/.github/CONTRIBUTING.md) about how to report domains.
- [X] I've checked the [database folder](https://github.com/Andre601/anti-scam-database/tree/main/database) for already existing domains.

### Domain

dlscord-nltro.com

### Affected platforms

Discord

### Proof

Just look

**Comment by Andre601** [comment]
"Just look" is not a valid proof, so please give some valid proof next time.
I'll accept it this time, because it's obvious, but for the next time please follow the template properly.
