### ISSUE TITLE
2 new domains to add

### ISSUE THREAD

**Issue by LagClear** [Andre601/anti-scam-database#4]
### Domain

nitroos-frieie.ru discorcd.click discorb.blog

### Affected platforms

Discord

### Proof

https://adamh.tech/2021/08/Discord_vGufsNDqbf.png
https://media.discordapp.net/attachments/164618267586068480/879380861559115806/image0.png?width=312&height=676
https://images-ext-2.discordapp.net/external/4Ant5uudEhEErHXwkqGZiPysOpz7wMNO--TFnBa09MI/https/adamh.tech/2021/08/Discord_7k7JtrbkvL.png

**Comment by Andre601** [comment]
Please make one issue per domain, as mentioned in the [Contributing file](https://github.com/Andre601/anti-scam-database/blob/main/.github/CONTRIBUTING.md) next time.

Also, discorcl.click is [already added](https://github.com/Andre601/anti-scam-database/blob/main/database/2021/discorcl.click-23.08.json)
